AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tfl-email

  Sample SAM Template for tfl-email

Parameters:
  S3BucketName:
    # Bucket for storing emails from SES
    Type: String
  GCPSecretName:
    # Secret name for GCP Credentials
    Type: String
    Default: gcp-credentials
  GCPProjectName:
    # GCP Project Name
    Type: String
  GCPLocation:
    # GCP Location
    Type: String
  TelegramBotToken:
    # Telegram Bot Token for sending message
    Type: String
  TelegramChatId:
    # Telegram chat ID for sending the summary
    Type: String
  SummaryTableName:
    # Table name for storing summaries
    Type: String
    Default: tfl-emails-summary

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  SummariseTflEmailFunction:
    Type: AWS::Serverless::Function
    Connectors:
      TableConn:
        Properties:
          Destination:
            Id: SummaryTable
          Permissions:
            - Write
    Properties:
      CodeUri: summarise_tfl_email/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Policies:
        - S3ReadPolicy:
            BucketName:
              Ref: S3BucketName
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn:
              Ref: GcpCredentialsSecret
      Environment:
        Variables:
          S3_BUCKET_NAME:
            Ref: S3BucketName
          GCP_PROJECT:
            Ref: GCPProjectName
          GCP_SECRET_NAME:
            Ref: GCPSecretName
          GCP_LOCATION:
            Ref: GCPLocation
          TELEGRAM_BOT_TOKEN:
            Ref: TelegramBotToken
          TELEGRAM_CHAT_ID:
            Ref: TelegramChatId
          SUMMARY_TABLE_NAME:
            Ref: SummaryTableName
      MemorySize: 512

  GcpCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "Credentials for GCP for LLM queries"
      Name:
        Ref: GCPSecretName

  SummaryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "week-id"
          AttributeType: "S"
          # format: 'YYYY-WW' where YYYY is the year and WW is week number
      KeySchema:
        -
          AttributeName: "week-id"
          KeyType: "HASH"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: True
      TableName:
        Ref: SummaryTableName
      BillingMode: "PAY_PER_REQUEST"
