AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tfl-email

  Sample SAM Template for tfl-email

Parameters:
  S3BucketName:
    # Bucket for storing emails from SES
    Type: String
  GCPSecretArn:
    # ARN for secret manager for storing GCP Credentials
    Type: String
  GCPSecretName:
    # Secret name for GCP Credentials
    Type: String
  GCPProjectName:
    # GCP Project Name
    Type: String
  GCPLocation:
    # GCP Location
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Policies:
        - S3ReadPolicy:
            BucketName:
              Ref: S3BucketName
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn:
              Ref: GCPSecretArn
      Environment:
        Variables:
          S3_BUCKET_NAME:
            Ref: S3BucketName
          GCP_PROJECT:
            Ref: GCPProjectName
          GCP_SECRET_NAME:
            Ref: GCPSecretName
          GCP_LOCATION:
            Ref: GCPLocation
      MemorySize: 512

Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
